import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

import css from './PrivacyPolicy.css';

const PrivacyPolicy = props => {
  const { rootClassName, className } = props;
  const classes = classNames(rootClassName || css.root, className);

  // prettier-ignore
  return (
    <div className={classes}>
      <p className={css.lastUpdated}>Last updated: November 24, 2019</p>

      <p>
        It is Boxitonline's policy to respect your privacy regarding any information we may collect while operating our websites.
      </p>

      <p>
        At Boxitonline, we are committed to safeguarding your privacy. This privacy policy provides information on the processing of 
        personal data by Boxitonline, hereafter Boxitonline, we or us. 
        We want you to feel secure when we are collecting and sharing your data and therefore, we want you to know how we collect, use, 
        share, and keep the information about you and the choices that are available to you as a data subject. 
        As such, this privacy policy is concerned with how we handle the personal data of users of Boxitonline (the Privacy Policy). 
        Your use of our website and services (the Services) and any dispute arising over privacy is subject to this Privacy Policy and 
        any of our applicable terms and conditions for the use of our services. 
      </p>

      <p>
        We reserve the right to, at all times, and without any particular notification, make changes to this Privacy Policy. 
        We might need to do so in the case of new developments, activities, online services, or when the applicable laws are amended. 
        We therefore advise you to regularly check this Privacy Policy to make sure you are up to date on any possible adjustments.  
      </p>

      <h2>1. When does this Privacy Policy apply?</h2>
      <p>
        This Privacy Policy is applicable to the processing of personal data of users by Boxitonline and possibly other individuals. 
        This Privacy Policy does not apply to the processing of data of employees the context of their employment or 
        assignment relationship at Boxitonline. 
      </p>

      <p>
        Boxitonline is committed to adequately protecting your personal data in accordance with the applicable laws and regulations, 
        regardless of your location and where we process it. 
        Similarly, we are committed to providing the appropriate protection framework when transferring your data outside of the EEA. 
      </p>

      <h2>2. Which types of personal data do we collect and why?</h2>
      <p>
        <ul>
          <li>
            (1) To deliver you our website’s functionalities and for their technical and functional management
            <p>
              <ul>
                <li>
                  <p>
                    (i) What does this purpose encompass?
                  </p>

                  <p>
                    For any person that accesses and uses our website, we process technical data to be able to offer you all our website’s 
                    functionalities and to allow our website’s administrators to manage and improve our website’s performance. 
                    If you enter data into our website, such as your location to receive relevant information and functionalities, 
                    we process this data to provide you with the requested information or functionalities. 
                  </p>
                </li>

                <li>
                  <p>
                    (ii) What legal ground justifies the processing of personal data for this purpose?
                  </p>

                  <p>
                    We process your personal data for this purpose based our legitimate interest. 
                    We do so to improve our overall marketing and communication efforts and to inform and update key stakeholders. 
                  </p>
                </li>

                <li>
                  <p>
                    (iii) Which personal data do we process for this purpose?
                  </p>

                  <p>
                    For this purpose, we process any personal data that you have entered into our website yourself, 
                    or that is generated by the functionalities described under (i), which includes your IP-address and the internet browser you use. 
                    Moreover, we make use of Google Analytics and Facebook Analytics to register the pages you visited on our website, your click- and surf behaviour and 
                    the length of your session, yet in a way untraceable to an individual person. 
                  </p>
                </li>

                <li>
                  <p>
                    (iv) How long will we hold on to your personal data?
                  </p>

                  <p>
                    We will store personal data gathered for this purpose for a maximum of 1 year. 
                    After this period, we will permanently delete your personal data from our systems.
                  </p>
                </li>
              </ul>
            </p>
          </li>

          <li>
            (2) To allow you to contact us or connect with us (e.g. on social media)
            <p>
              <ul>
                <li>
                  <p>
                    (i) What does this purpose encompass?
                  </p>

                  <p>
                    Boxitonline maintains active accounts on several social media platforms. When you contact us via one of these platforms, 
                    we process your personal data in order to answer your queries, to respond to the messages or requests, 
                    and subsequently to contact you in relation to any campaigns we might run through these platforms from that point onwards. 
                  </p>
                </li>

                <li>
                  <p>
                    (ii) What legal ground justifies the processing of personal data for this purpose?
                  </p>

                  <p>
                    We process your personal data based on a legitimate interest. 
                    Being able to communicate with (potential) users is vital to our business. 
                    It can also improve our overall marketing and communication efforts. 
                  </p>
                </li>

                <li>
                  <p>
                    (iii) Which personal data do we process for this purpose?
                  </p>

                  <p>
                    For this particular purpose, we process via the communication channel which you have chosen to use to connect with us, 
                    and we process the personal data you used to connect with us and chose to supply to Boxitonline. 
                    This includes your (user) name, address, email address, gender, and any additional personal data you included in your message. 
                  </p>
                </li>

                <li>
                  <p>
                    (iv) How long will we hold on to your personal data?
                  </p>

                  <p>
                    We will store the data collected for this purpose for a maximum of 10 years. 
                    After this period, we will permanently delete all this data from our systems.
                  </p>
                </li>
              </ul>
            </p>
          </li>

          <li>
            (3) For answering your questions and handling of complaints
            <p>
              <ul>
                <li>
                  <p>
                    (i) What does this purpose encompass?
                  </p>
                  
                  <p>
                    If you get in touch with us at our office(s), via a contact form, or contact any of our employees in any possible form, 
                    we will use your personal data in order to reply to and answer your question or to respond to and handle a complaint.
                  </p>
                </li>

                <li>
                  <p>
                    (ii) What legal ground justifies the processing of personal data for this purpose?
                  </p>
                  
                  <p>
                    We process your personal data based on consent and legitimate interest. In this case, the legitimate interest is constituted by 
                    our intent to carefully deal with your complaints and questions. 
                  </p>
                </li>

                <li>
                  <p>
                    (iii) Which personal data do we process for this purpose?
                  </p>
                  
                  <p>
                    To the end of this purpose we process your name, contact details, your correspondence with Boxitonline about your question or 
                    complaint and all other personal data which are necessary to answer your question or to handle your complaint. 
                  </p>
                </li>

                <li>
                  <p>
                    (iv) How long will we hold on to your personal data?
                  </p>
                  
                  <p>
                    We will retain your personal data for as long as we need to execute your request or handle the complaint, 
                    plus a maximum of 1 month, after which the data will be deleted from our systems. 
                  </p>
                </li>
              </ul>
            </p>
          </li>

          <li>
            (4) To ensure correct enforcement and respect of your rights included in this Privacy Policy
            <p>
              <ul>
                <li>
                  <p>
                    (i) What does this purpose encompass?
                  </p>
                  
                  <p>
                    As a result of the rights you have, which can be found in Section 7 of this Privacy Policy, 
                    we process your personal data in order to execute and administer your requests to us in relation to these rights. 
                    For example, if you want to exercise your right to be forgotten, we need to register a minimum amount of data 
                    in order to make sure that we do not contact you anymore.
                  </p>
                </li>

                <li>
                  <p>
                    (ii) What legal ground justifies the processing of personal data for this purpose?
                  </p>
                  
                  <p>
                    Processing of this personal data is based on our legitimate interest. 
                    The legitimate interest we have is that we intent to respect your choices and thus, 
                    we want to ensure that if you exercise your right to be forgotten, we will never contact you again for any purpose. 
                  </p>
                </li>

                <li>
                  <p>
                    (iii) Which personal data do we process for this purpose?
                  </p>
                  
                  <p>
                    For this purpose, we process contact details such as your address and email address, 
                    and personal details such as your name. 
                  </p>
                </li>

                <li>
                  <p>
                    (iv) How long will we hold on to your personal data?
                  </p>
                  
                  <p>
                    Due to the nature of this purpose, we need to hold on to this data for an unlimited period.
                  </p>
                </li>
              </ul>
            </p>
          </li>

          <li>
            (5) For the conclusion and execution of agreements with users
            <p>
              <ul>
                <li>
                  <p>
                    (i) What does this purpose encompass?
                  </p>
                  
                  <p>
                    We use personal data for the purpose of entering into relationships with Boxitonline users, 
                    and to perform any contractual obligations under the contract that we have with users. 
                    We might also use your personal data for the implementation and execution of our Services. 
                  </p>
                </li>

                <li>
                  <p>
                    (ii) What legal ground justifies the processing of personal data for this purpose?
                  </p>
                  
                  <p>
                    We process personal data for this purpose based on our contract with you and legitimate interest. 
                    We do so on the basis of the contract that you have engaged in with Boxitonline relating to the provision 
                    of the specific service between you and Boxitonline. 
                    Our legitimate interest to process your data follows from our intent to comply with applicable law.
                  </p>
                </li>

                <li>
                  <p>
                    (iii) Which personal data do we process for this purpose?
                  </p>
                  
                  <p>
                    For this purpose, we process your contact details such as your address, phone number, and email address, 
                    personal details such as name and date of birth, payment and credit information, tax information, 
                    order history and other data stored in our database with all relationships of Boxitonline.
                  </p>
                </li>

                <li>
                  <p>
                    (iv) How long will we hold on to your personal data?
                  </p>
                  
                  <p>
                    Your personal data will be hold on to for 7 years after the end of our relationship with you. 
                    After this term, your personal data will be deleted from our systems. 
                  </p>
                </li>
              </ul>
            </p>
          </li>

          <li>
            (6) For relationship management and marketing
            <p>
              <ul>
                <li>
                  <p>
                    (i) What does this purpose encompass?
                  </p>
                  
                  <p>
                    Boxitonline could possibly use the information stored in its contractual relationship database to send you newsletters, 
                    as well as to provide customer services and perform account management. 
                    We also use your personal data for the development, execution, and analysis of market surveys and marketing strategies. 
                  </p>
                </li>

                <li>
                  <p>
                    (ii) What legal ground justifies the processing of personal data for this purpose?
                  </p>
                  
                  <p>
                    We process your personal data for this purpose based on your consent. 
                    You can withdraw your consent at any time, without this affecting the lawfulness of processing based on consent before withdrawal. 
                  </p>
                </li>

                <li>
                  <p>
                    (iii) Which personal data do we process for this purpose?
                  </p>
                  
                  <p>
                    For this purpose, we process you contact details such as your address and email address, 
                    personal details such as your name and date of birth, contact preferences, payment information, order history, 
                    and correspondence with us. 
                  </p>
                </li>

                <li>
                  <p>
                    (iv) How long will we hold on to your personal data?
                  </p>
                  
                  <p>
                    Personal data will be retained for a maximum of 10 years after the termination of our relationship. 
                    After this term, your personal data will be deleted from our systems.
                  </p>
                </li>
              </ul>
            </p>
          </li>
        </ul>
      </p>

      <h2>3. Cookies</h2>
      <p>
        A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides 
        to the website each time the visitor returns. Boxitonline uses cookies to help Boxitonline identify and track visitors, 
        their usage of Boxitonline website, and their website access preferences. 
        Boxitonline visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies 
        before using Boxitonline’s websites, with the drawback that certain features of Boxitonline’s websites may not function properly 
        without the aid of cookies.
      </p>

      <h2>4. Special personal data</h2>
      <p>
        We insist on not processing any personal data of minors, unless this is explicitly consented to by a parent or legal guardian. 
        However, as it is hard to detect whether we are doing so, we strongly encourage you to inform us if you have reason to believe 
        we process the personal data of a minor. We will delete this personal data instantly. 
      </p>

      <h2>5. Who has access to your personal data?</h2>
      <p>
        Boxitonline is committed to securing your personal data and has taken the necessary steps in this regard. 
        Only our employees, interns, and volunteers are authorised to access personal data, yet, 
        only to the extent necessary to properly perform their individual jobs. 
      </p>

      <p>
        With every third party who, on our behalf, processes personal data, we have entered into the required data processing agreements. 
        Boxitonline only shares personal data with third parties if it is necessary to serve its applicable purpose as set out above. 
        In all cases, we will ensure that third parties with access to your personal data have implemented appropriate technical and 
        organizational safeguards to maintain our envisioned level of privacy and security. 
        We furthermore insist that all data protection and privacy laws are adhered to at all times.
      </p>

      <p>
        If your personal data is transferred to a recipient in a country outside the EEA or where an adequate level of protection of 
        personal data is not provided for, Boxitonline will take measures to ensure that your personal data is adequately protected in 
        those countries as well, such as entering into the EU Standard Contractual Clauses with these third parties.
      </p>

      <p>
        When a third party processes your personal data, they can only do so following Boxitonline’s instructions. 
        They therefore act as our data processor. 
        We enter into the necessary agreement with the data processing where we include obligations to ensure your personal data is 
        processed solely in order for the data processor to fulfil its duty to provide services to us.
      </p>

      <p>
        In any other case, your personal data will not be supplied to third parties, except where mandated by law.
      </p>

      <h2>6. Security</h2>
      <p>
        Your personal data will be stored securely at all times. We value the protection of your privacy. 
        We treat personal data very carefully, and, possibly together with third parties, we ensure that appropriate organisational and 
        technical protection measures are implemented to safely store personal data. 
        In this manner, we ensure that the personal data is only accessible to those particular individuals who are authorized 
        based on their job function, and therefore is only used for its intended purpose. 
        Additionally, we have implemented measures to guarantee your safe visit to and use of our websites. 
        In doing so, we prevent any abuse of your data. These measures include computer safeguards and secured files and facilities. 
      </p>

      <p>
        Boxitonline has taken the necessary technical and organizational measures to prevent, signal, rapport, 
        and handle any breach in its data protection. 
        In the event that a data breach does occur, however, Boxitonline will, without undue delay, and where feasible, 
        not later than 72 hours after having become aware of it, notify the personal data breach to the relevant Data Protection Authority. 
      </p>

      <h2>7. Accessing, correcting or removing personal data</h2>
      <p>
        You have the right to access, correct, or remove your personal data that we have stored. 
        You also have the right to withdraw your previously given consent to the processing of your personal data, 
        or to object to the processing of your personal data by Boxitonline. 
        Finally, you have the right to have a file sent to you, containing details of which of your personal data we have stored. 
        You can send us a request to receive such a file in writing. Any request is subject to the applicable law, 
        which means that we might need to keep the personal data stored.
      </p>

      <p>
        We also want to inform and remind you of the ability to issue a formal complaint at the national Data Protection Authority.
      </p>

      <p>
        If you object to Boxitonline using your personal data, want your personal data to be forgotten, 
        want to withdraw your previously given consent to process your personal data, 
        or you have a different enquiry concerning your personal data, you can at any time send a request to:
      </p>

      <p>
        <ul>
          <li>Boxitonline</li>
          <li>Verstraat 32 - 2</li>
          <li>admin@boxitonline.com</li>
        </ul>
      </p>

      <h2>External links</h2>
      <p>
        Our website could sometimes display links to other websites. 
        We are not responsible for the privacy policy that this other website adheres to, nor its content. 
        We advise you to inform yourself by reading the privacy policies on these websites. 
      </p>

      <h2>Any questions?</h2>
      <p>
        In the event you still have questions after reading this Privacy Policy, or when you have any suggestions or comments about 
        its content, you can always contact us at: admin@boxitonline.com
      </p>
    </div>
  );
};

PrivacyPolicy.defaultProps = {
  rootClassName: null,
  className: null,
};

const { string } = PropTypes;

PrivacyPolicy.propTypes = {
  rootClassName: string,
  className: string,
};

export default PrivacyPolicy;
